apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elasticsearch
  labels:
    app.kubernetes.io/name: filebeat
    app.kubernetes.io/instance: filebeat
    app.kubernetes.io/version: "7.10.1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: filebeat
      app.kubernetes.io/instance: filebeat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: filebeat
        app.kubernetes.io/instance: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.10.1
          env:
            - name: LOGSTASH_URL
              value: "logstash:5044"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: data
              mountPath: /usr/share/filebeat/data
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: "400m"
              memory: "1Gi"
            limits:
              cpu: "600m"
              memory: "2Gi"
      volumes:
        - name: config
          configMap:
            name: filebeat-configuration
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
